gowalla-v1:
  # seed: 19972022
  n_timesteps: 28800000
  batch_size: 64
  n_steps: 2048
  gamma: 0.99
  learning_rate: 6.561348669308759e-05
  ent_coef: 2.4121304912071486e-06
  clip_range: 0.3
  n_epochs: 10
  gae_lambda: 0.8
  max_grad_norm: 0.8
  vf_coef: 0.24173147441088982
  n_envs: 5
  policy: rl_zoo3.aoi_cbu.custom_multi_input.CustomMultiInputPolicy
  policy_kwargs: "dict(
      net_arch=[256, 256],
      features_extractor_class='simp',
      features_extractor_kwargs=dict(
          linear_dims=[64, 64],
          act_func='tanh'
      )
  )"
  normalize: "dict(norm_obs_keys=['weight', 'AoI'])"
